### PR TITLE
Remove globalize

### PR DESCRIPTION
**Pull request by tvdeyen**
**[WORK IN PROGRESS]**

## Proposal for removing the globalize functionality

I removed everything that has to do with globalization/translation of spree models and only kept the locale files for the languages and some basic functionality for it (i.e. the locale switching select box, rake tasks).

I also removed the routing filter gem, because IMO that also belongs into the yet to be introduced spree_globalize gem.

Please take a look and let's discuss, if this is the right way to go.

Cheers :beers: 

PS: I will rebase the branch after everything is fine. So please don't complain about the not so meaningful commit messages :)

### CODE REVIEW

**Comment by tvdeyen** [comment]
could someone of the @spree-contrib/owners please create a new repo `spree_globalize` where I can contribute and move the model translations functionality from `spree_i18n` into.

Thanks :cake:

**Comment by alepore** [comment]
can you clarify what's the target use case of spree_i18n without spree_globalize?
to have a single language that's not english or to have multiple languages without content translation?

**Comment by alepore** [comment]
the locale switcher and routing-filter should go on the same gem imho, it's the same functionality (setting the request locale)

**Comment by mamhoff** [comment]
@alepore We're building a shop with exclusively German content, and we want to keep updating and get the newest and best translations. Globalize is not important for us, as there's only a single language.

**Comment by alepore** [comment]
@mamhoff clear, so maybe it's better to remove the locale switcher and just keep translation files here?

**Comment by mamhoff** [comment]
@alepore: Previous answer was "what's the use case". This one is about "What about routing + locale switcher" :)

@alepore I actually agree here: Locale switching and Routing should stay in `spree_i18n` - I can imagine a use case for a shop with universally understandable products that don't need localized data, but might want a localized shop interface anyways.

**Comment by tvdeyen** [comment]
@mamhoff good point. 

@alepore Imagine a shop with international product descriptions (english) and a visitor coming from a foreign language (maybe a one you don't have product translations for), but you want the GUI and the checkout to be localized.

So, keeping the locale switcher **and** the routing filter makes totally sense to me now.

Thanks for pointing that out guys.

**Comment by tvdeyen** [comment]
@alepore the use case is shops that only has one language (i.e. Italian ^_^) that is not the spree default language (English), so you will need translation files for the backend and the frontend GUI, but you *do not* need translated model data, because your products always are displayed and therefore entered in Italian.

**Comment by tvdeyen** [comment]
… and you need localized Dates, Currencies, etc.

**Comment by alepore** [comment]
:+1: makes sense

**Comment by tvdeyen** [comment]
Oh, I think it is not a good idea to also remove the `SpreeI18n::Config.supported_locales` configuration, because I don't think that all shops always want to support all `I18n.available_locales`, **but** I think we shouldn't keep the administration forms for that feature, because there are no user provided translations (via globalize) and therefore should be set by the developer in an initializer. 

Also, we probably will get some conflicts with `spree_globalize` in the future, because this will also have this functionality.

What do you think?

**Comment by mamhoff** [comment]
I think `spree_globalize` should just be that - model data translations - and everything else should stay in `spree_i18n`. That way, there will be no conflicting stuff between the two gems, and `spree_globalize` can just depend on `spree_i18n`. I say keep it, and do not have it in `spree_globalize`.

I can not imagine a shop wanting (and maintaining) product translations but no UI translations.

**Comment by tvdeyen** [comment]
That will give conflicts: Imagine a store that has only two model translations but 10 GUI translations via the locale files. How will you set the available locales if we only have configuration options for `available_locales` and `supported_locales` in `spree_i18n`?

**Some Background:** The user sets the `Spree::I18n.supported_locales` via backend administration if she decides the model translation is ready for production. The `Spree::I18n.available_locales` are all available locales that are  ready to be translated **and** also used for the locale select drop down (aka. the GUI translation yml files).

So we either need to introduce three options (:scream:), or way better IMO, we remove the administration for `supported_locales` into `spree_globalize`. 

We don't want to confuse the users, don't we?

**Comment by tvdeyen** [comment]
So, we would have `SpreeI18n::Config.available_locales` with a default of `I18n.available_locales`, so the user can decide which GUI translation should be available and in `spree_globalize` we have `Spree::Globalize::Config.supported_locales` with a default of `SpreeI18n::Config.available_locales`. So the user can decide which model translations are ready for production.

:+1: for having `spree_i18n` as dependency for `spree_globalize`

D'accord?

**Comment by mamhoff** [comment]
Sounds good to me! Go for it! :+1:

**Comment by alepore** [comment]
YO :100:

**Comment by kennyadsl** [comment]
It seems like everything makes sense here! :smile: 

Just thinking loud: if needed we could probably build another "wrapper" extension that includes both `spree_i18n` and `spree_globalize` with some code that makes them play nicely together. IMHO it could make sense if this helps keeping both extensions independent so everyone can use them as needed.

**Comment by tvdeyen** [comment]
@kennyadsl I vote for `spree_globalize` depending on `spree_i18n`, because like @mamhoff already said: We can't image a store, that wants to have model translations but no GUI translations.

Introducing a third gem is much more overhead and need necessary IMO.

**Comment by tvdeyen** [comment]
@spree-contrib/spree_i18n I reverted the locale select and routing filter stuff. Also I added the possibilty to administrate `available_locales`, like discussed above.

**Please do *not* merge** until `spree_globalize` is published, otherwise we will make a lot of people angry :sunglasses: 

PS: Could please someone @spree-contrib/owners create a new repo for `spree_globalize`? Otherwise I will create one at https://github.com/magiclabs and we need to transfer ownership later.

Thanks for all your feedback

**Comment by JDutil** [comment]
Created https://github.com/spree-contrib/spree_globalize

**Comment by JDutil** [comment]
Great discussion / feedback.  I definitely agree with leaving locale switching here, and making spree_globalize depend on spree_i18n.

**Comment by alepore** [comment]
:+1:  spree_globalize is green

**Comment by alepore** [comment]
so... can we merge this? :)

**Comment by tvdeyen** [comment]
@alepore is spree_globalize ready, yet? Tests are green, ok, but is everything working like expected?

Especially the changed configuration options. Do we need some kind of migration path for them?

**Comment by alepore** [comment]
@tvdeyen not sure it's 101% working, if not we probably need some new test.
but i think we/users will find out quicker when merged.
some PR are waiting this, other should be moved to spree_globalize, some users are already using temporary branches... imho we should make the switch to accelerate things

**Comment by tvdeyen** [comment]
Good point. And it's the master branch, so `¯\_(ツ)_/¯`

:+1: for merge

**Comment by JDutil** [comment]
Thanks guys.

**Comment by tvdeyen** [comment]
Woooooohooo :tada: :balloon:

**Comment by jumski** [comment]
Keeping routing-filter in `spree_i18n` makes impossible to define `exclude:` rules, becase the call to `filter :locale` in spree_i18n is always executed after the call in host app routes.rb, which overwrites any excludes set

i am struggling with this today for few hours and found no workaround yet, imo it should at last be possible to disable it with some config, so host app can enable it by itself

**Comment by jumski** [comment]
i have deepened my understanding of what is happening under the hood, no overrides are happening, but locale filter is included in spree routes, and using it in host app involves `exclude:`ing all the spree routes in order to not end up with double prefixed spree paths (`/en/en/cart` anyone? :sunglasses: )

routing-filter is non trivial lib and some understanding of rails routing is necessary in order to use it / debug it (i've burned many hours on investigating issues with this), which leads to conclusion that it would be better to have it disabled by default, with a config to enable it, or just a simple README entry, because enabling it for spree routes is as easy as putting this snippet in host app's routes.rb:

```ruby
Spree::Core::Engine.routes.draw do
  filter :locale
end
```

**Pull request merged**
