### PR TITLE
Add translation to whitelist.

### PR DESCRIPTION
**Pull request by JDutil**

### CODE REVIEW

**Comment by mvz** [comment]
You need an explicit reciever to make this work, or else Ruby thinks you want to assign a local variable. You'll also want to set the class variable explicitely if it's unset, because some models may not have any whitelisted associations to start with:

```ruby
    included do |klass|
      klass.whitelisted_ransackable_associations ||= []
      klass.whitelisted_ransackable_associations |= ['translations']
    end
```

**Comment by mvz** [comment]
There's one spec left that fails because 'description' isn't whitelisted for Product. changing it to 'slug' makes the spec pass without removing its usefulness.

**Comment by JDutil** [comment]
Should be all set.

**Comment by rsmithlal** [comment]
This breaks spree 2.3.

**Comment by alepore** [comment]
@rsmithlal what error do you get? can you try the latest revision?

**Comment by rsmithlal** [comment]
We're using spree-I18n as part of our spree extension in 2.3. We're in the process of migrating to 2.4 for our client, but the latest revision of this version of the gem introduced the whitelisted ransackable attributes line which broke our extension when we tried to deploy a fix for something unrelated into production. I removed this line from my fork and used it for the build, and it works fine now. The error we got was that there was no whitelisted_ransackable_associations method on the instance it was called on from translatable.rb. I'm not sure the exact wording because it was my boss that encountered the bug.

**Pull request merged**
