### PR TITLE
Updates taxon_tree_menu override.

### PR DESCRIPTION
**Pull request by tvdeyen**
Spree 3.0 added new icon classes. This updates the coffee file that
overwrites the original spree core one.

Follow up to https://github.com/spree/spree/pull/6378

### CODE REVIEW

**Comment by tvdeyen** [comment]
@JDutil as stated in https://github.com/spree/spree/pull/6378

**Comment by JDutil** [comment]
Should probably merge to 3-0-stable as well.

**Comment by tvdeyen** [comment]
3-0-stable uses the old jstree theme and I don't think the Glyphicons will fit into that.

**Comment by tvdeyen** [comment]
And the old icons will silently be ignored, so it don't look broken.

**Comment by JDutil** [comment]
Sorry I thought I merged the new theme into 3-0-stable as well, but that was only my local repo it didn't end up pushing upstream.  It is now though https://github.com/spree/spree/commit/7d4073a8ba34c7deeaeca13b6bcd1b1a17dea8aa

**Pull request merged**
