### PR TITLE
Bulgarian

### PR DESCRIPTION
**Pull request by vkdimitrov**
update bulgarian translation

### CODE REVIEW

**Comment by damianlegawiec** [comment]
Hi @vkdimitrov can you also submit this PR for master branch too? Thanks!

**Comment by vkdimitrov** [comment]
I have a problem with unresolved dependencies when try __bundle install__ on the master branch. Is this a problem, or I can merge and pull request?

**Comment by damianlegawiec** [comment]
@vkdimitrov working on it :)

**Comment by damianlegawiec** [comment]
@vkdimitrov done!

**Pull request merged**
