### PR TITLE
States, shipping methods and payment methods are now translatable + Missing translations in fr.yml

### PR DESCRIPTION
**Pull request by JoeDupuis**

### CODE REVIEW

**Comment by JDutil** [comment]
Would you mind addressing the format to follow 2 soft spaces for tabs?  Also would be good to add some feature specs for each new model in:
https://github.com/spree-contrib/spree_i18n/blob/master/spec/features/admin/translations_spec.rb

**Comment by twistedjoe** [comment]
Will try when I have a minute.

**Comment by alepore** [comment]
oh nice, didn't saw this.
i just implemented payment methods translations, pretty similar, you can look at my commit https://github.com/alepore/spree_i18n/commit/ab551764fdb3b3c1ac7d051b818e5fe69bf475bf :

- there are some payment methods specs
- i think i managed how to avoid controller overrides with this line: https://github.com/alepore/spree_i18n/blob/ab551764fdb3b3c1ac7d051b818e5fe69bf475bf/app/views/spree/admin/translations/payment_method.html.erb#L18

the fact is current code doesn't work very well with STI models, so the `type` gets deleted every time

**Comment by rbngzlv** [comment]
Hi @alepore and @JDutil ! This pull request has been inactive for two months. I have cherrypicked the commit commented above (https://github.com/alepore/spree_i18n/commit/ab551764fdb3b3c1ac7d051b818e5fe69bf475bf) into my fork and all seems ok.

We need to wait to resolve this pull request? Or I can open a new pull request for merge the @alepore  commit from my fork? @alepore do you prefer to do the pull request from your fork?

If it seems right to create a new pull request, also I will create another pull request for the shipping methods based on the commit available here, but with specs added and indentation fixed.

Then, the things remaining in this pull request will be:
- Made States translatable
- Some french translations

**Comment by JDutil** [comment]
Feel free to submit a new PR in favor of this one, but I'd still like to get my feedback on specs and formatting fixed.

**Pull request closed without merging**
