### PR TITLE
3-0-stable ransack and translations

### PR DESCRIPTION
**Pull request by huoxito**
This is https://github.com/spree-contrib/spree_i18n/pull/532 for 3-0-stable. Pointint to 4-2-stable here because the fix will only be released on 4.2.4.

### CODE REVIEW

**Comment by alepore** [comment]
:heart_eyes: thanks for the work on this

**Comment by mvz** [comment]
With this change I'm running into issues for older records that fall back to the non-translated attribute.

**Comment by mvz** [comment]
To work around my problem, I created this alternative implementation:

```ruby
module Concerns::RansackableTranslations
  extend ActiveSupport::Concern

  included do |klass|
    translated_attribute_names.each do |t|
      ransacker t do |parent|
        Arel.sql("coalesce(#{translations_table_name}.#{t}, #{table_name}.#{t})")
      end
    end

    klass.class_eval do
      class << self
        alias_method_chain :ransack, :translations

        alias :search :ransack unless respond_to? :search
      end
    end
  end

  class_methods do
    def ransack_with_translations(params = {}, options = {})
      joins(:translations).ransack_without_translations(params, options)
    end
  end
end
```

**Comment by huoxito** [comment]
@mvz any chance you could provide a test example for the issue pls? I didn't get it. It was my intention actually to have merged this already but I keep missing it, will hold for a bit until we understand the problem.

**Comment by mvz** [comment]
@huoxito Sure.

**Comment by mvz** [comment]
@huoxito see #602 for a test case and implementation. I took the liberty of removing the use of Rails git repo to speed up bundle install.

**Comment by mvz** [comment]
@huoxito something weird happening there on postgres.

**Comment by mvz** [comment]
@huoxito Looks like my implementation suffers from this (from Ransacker's README):
> Please note that for many databases, a sort on an associated table's columns may result in invalid SQL with distinct: true -- in those cases, you're on your own, and will need to modify the result as needed to allow these queries to work.

In any case, my added spec demonstrates the issue I'm running into in my app.

**Comment by mvz** [comment]
@huoxito I ran into some other trouble with my solution and have now found a different one. I will create a PR for it.

**Comment by huoxito** [comment]
closing in favor of https://github.com/spree-contrib/spree_i18n/pull/602 (better implementation) which I want to merge tonight

**Pull request closed without merging**
