### PR TITLE
Update Polish locale

### PR DESCRIPTION
**Pull request by pusewicz**
/cc @huoxito @JDutil 

This is the first PR of many to come ;)

### CODE REVIEW

**Comment by tvdeyen** [comment]
Are these pull request all related to polish translations? Then maybe one pull request with several commits would be better? What do you think @JDutil @huoxito ?

**Comment by pusewicz** [comment]
@tvdeyen Yeah maybe, but I translate and push as I go and find missing translations.

**Comment by tvdeyen** [comment]
No problem, you can always rebase your branch and force push. So that your PR includes only useful commits.

**Comment by JDutil** [comment]
Yea feel free to continue pushing polish updates as you do them to the same PR if your waiting for us, but will merge this now.

**Pull request closed without merging**
