### PR TITLE
Danish: Added various missing tranlsations.

### PR DESCRIPTION
**Pull request by kaspernj**
Also removed unnecessary white-spaces (editor did that automatically).

I want to add more, but I would like some feedback on the few I made already first...

### CODE REVIEW

**Comment by JDutil** [comment]
I think the empty keys should just be removed altogether in the future for fallback to work properly right @futhr ?

**Comment by futhr** [comment]
No, they should exist as far I know, that's why its called "fallback-on-empty-keys". I can be wrong, but localeapp add empty keys and I assume they have researched that to keep the extra payload.

**Comment by futhr** [comment]
Also its actually most logic for empty keys to exist, otherwise its a nightmare to fill them in development perspective. But I do believe it can exist without, e.g. `en-AU` etc. just use a couple of changed keys and thereby its an overhead to actually have full set of empty keys in those types of locales.

**Comment by JDutil** [comment]
Yea what I actually was remembering from before was that we removed the english translation from being in the file, but we still left the keys.

**Comment by futhr** [comment]
I have cleaned up `2-3-stable` and `master` but not `2-4-stable` branch from unused keys and English translations in non English locales.

**Pull request merged**
