### PR TITLE
Capitalize first char in IT translation

### PR DESCRIPTION
**Pull request by delphaber**

### CODE REVIEW

**Comment by delphaber** [comment]
I don't think my commit broke the test suite. Are there problems with travis configuration? :O

**Comment by damianlegawiec** [comment]
@delphaber it's Rails 5.1 in spree master (3.3.0), this needs some fixing and travis configuration bump - will do this week after returning from Italy ;)

**Comment by delphaber** [comment]
Happy holidays! :D

**Comment by damianlegawiec** [comment]
@delphaber master fixed & ready for Rails 5.1 / Spree 3.3 :) Holidays were great, can't wait to go back! :)

**Pull request merged**
