### PR TITLE
Update sk.yml

### PR DESCRIPTION
**Pull request by modreoci**

### CODE REVIEW

**Comment by alepore** [comment]
@modreoci can you check this error?
```#<Psych::SyntaxError: (/home/travis/build/spree-contrib/spree_i18n/lib/spree_i18n/../../config/locales/sk.yml): could not find expected ':' while scanning a simple key at line 576 column 7> (I18n::InvalidLocaleData)```

**Comment by modreoci** [comment]
There is missing space between the key and the value.

I'm new user on Github. Can you explain me how to correct it? I
unfortunately didn't find the way how to do it...

Radek Hrančík

2015-04-15 22:02 GMT+02:00 Alessandro Lepore <notifications@github.com>:

**Comment by alepore** [comment]
Did you edit it via the Github site?
I'm not sure there's a quick way to correct it from Github itself, you have to manually checkout and modify this branch.

Anyway, i did it for you, just added this to `master` and `3-0-stable`.
Thanks!

**Comment by modreoci** [comment]
Yes, I edited it via the Github site... Thnx ;-)

Radek Hrančík

2015-04-15 23:39 GMT+02:00 Alessandro Lepore <notifications@github.com>:

**Pull request closed without merging**
