### PR TITLE
add support for full page caching for spree 3.1.x

### PR DESCRIPTION
**Pull request by priyank-gupta**
- Supports full page caching without any breaking functionality with this extension.
- Updated development dependencies.

### CODE REVIEW

**Comment by tvdeyen** [comment]
Hey and thanks for the contribution.

You fixes some specs, added support for Circle CI artifacts and changed code to support a feature that many may not be ware of.

So please, before merging this in, could you split this up in [meaningful commit messages](http://chris.beams.io/posts/git-commit/)?

Thanks

**Comment by priyank-gupta** [comment]
@tvdeyen Sure, on it.

**Comment by priyank-gupta** [comment]
@tvdeyen Done!

**Comment by tvdeyen** [comment]
Ok, thanks. Fine by me hten

**Pull request merged**
