### PR TITLE
change to new hash syntax, rename keyword attr(reserved) to attribute…

### PR DESCRIPTION
**Pull request by priyank-gupta**
…, upgrade spree_core to 3.0.5, upgrade sass-rails to 5.0.0, bump version to 3.0.5

### CODE REVIEW

**Comment by tvdeyen** [comment]
@priyank-gupta thanks for this contribution. Could you please make three commits in stead of one large commit? That would help reading the git history. Thanks :blossom:

**Comment by priyank-gupta** [comment]
@tvdeyen Sure, on it.

**Comment by tvdeyen** [comment]
@priyank-gupta thank you!

**Comment by priyank-gupta** [comment]
@damianlegawiec Checking specs.

**Comment by priyank-gupta** [comment]
Fixed!!!

**Comment by Mafi88** [comment]
:+1:

**Pull request merged**
