### PR TITLE
Shipping methods translatable

### PR DESCRIPTION
**Pull request by rbngzlv**
Based on this pull request https://github.com/spree-contrib/spree_i18n/pull/517 with specs added and indentation fixed

### CODE REVIEW

**Comment by JDutil** [comment]
We should implement this against master not a stable branch as we want to avoid migrations and behavior changes in stable branches in order to ensure they stay stable.

**Comment by alepore** [comment]
@rbngzlv can you apply this PR for the master branch? (may need some minor templating changes)

**Comment by rbngzlv** [comment]
Sorry, I forgot this pull request. 

I have a new pull request prepared, but this commit https://github.com/spree/spree/commit/bb111595221f90caa3a688155825fb49071f9a33 is breaking the specs on master branch.

You want to fix this before I apply the new PR to the master branch?

**Comment by alepore** [comment]
Hey @rbngzlv, that problem should fixed now.
Please not we just moved all the globalize stuff on https://github.com/spree-contrib/spree_globalize , so please open the PR on that repo.

That's a fork of the spree_i18 code so apply changes to the new repo should be pretty straightforward.
Thanks!! :pray:

**Comment by rbngzlv** [comment]
@alepore Pull request done: https://github.com/spree-contrib/spree_globalize/pull/4

**Comment by JDutil** [comment]
Merged

**Pull request closed without merging**
